routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['middleware' => ['auth']], function() {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('teams', 'TeamsController');
    Route::resource('team_players', 'TeamPlayersController');

    //need these after search
    Route::post('/team_players', 'TeamPlayersController@index')->name('team_players.search');
    Route::post('/team_players/store', 'TeamPlayersController@store')->name('team_players.store');

    // routes for matches
    Route::resource('cricket_matches', 'CricketMatchesController');

    Route::get('/points', 'CricketMatchesController@points')->name('team.points');
});

app/Http/Controllers/CricketMatchesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\CricketMatches;
use App\Models\Team;
use Illuminate\Http\Request;
use Exception;

class CricketMatchesController extends Controller
{

    /**
     * Display a listing of the cricket matches.
     *
     * @return Illuminate\View\View
     */
    public function index()
    {
        $cricketMatchesObjects = CricketMatches::paginate($this->pageSize);
        return view('cricket_matches.index', compact('cricketMatchesObjects'));
    }

    /**
     * Display a points table of teams.
     *
     * @return Illuminate\View\View
     */
    public function points()
    {
        $teams = Team::pluck('team_name','id')->all();
        $team_data=array();
        foreach($teams as $key=> $team){
          // $key;
           $team_data[$key]['name']=$team;
           //$teams[]['matches']='2';
           $team_data[$key]['team_matches'] =  CricketMatches::where('team_one','=',$key)->orwhere('team_two','=',$key)->count();

           $team_data[$key]['team_no_result'] =  CricketMatches::where('team_one','=',$key)->where('match_result','=','')->orwhere('team_two','=',$key)->where('match_result','=','')->count();

           $team_data[$key]['team_win_count'] = CricketMatches::where('match_result','=',$key)->count();
           $team_data[$key]['team_loose_count'] = $team_data[$key]['team_matches'] - $team_data[$key]['team_win_count']-$team_data[$key]['team_no_result'];
        }
        // echo '<pre>';
        // print_r($team_data);
        // echo '</pre>';
        // echo '<br>';
        // die;
        return view('cricket_matches.matchPoints', compact('team_data'));
    }

    /**
     * Show the form for creating a new cricket matches.
     *
     * @return Illuminate\View\View
     */
    public function create()
    {
        $teams = Team::pluck('team_name','id')->all();
        return view('cricket_matches.create', compact('teams'));
    }

    /**
     * Store a new cricket matches in the storage.
     *
     * @param Illuminate\Http\Request $request
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        try {

            $data = $this->getData($request);
            $cricketMatches= CricketMatches::create($data);
            return redirect()->route('cricket_matches.edit',$cricketMatches->id )
                ->with('success_message', 'Cricket Matches was successfully added.');
        } catch (Exception $exception) {

            return back()->withInput()
                ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }

    /**
     * Display the specified cricket matches.
     *
     * @param int $id
     *
     * @return Illuminate\View\View
     */
    public function show($id)
    {
        $cricketMatches = CricketMatches::findOrFail($id);

        return view('cricket_matches.show', compact('cricketMatches'));
    }

    /**
     * Show the form for editing the specified cricket matches.
     *
     * @param int $id
     *
     * @return Illuminate\View\View
     */
    public function edit($id)
    {
        $cricketMatches = CricketMatches::findOrFail($id);
        $teams = Team::pluck('team_name','id')->all();
        return view('cricket_matches.edit', compact('cricketMatches','teams'));
    }

    /**
     * Update the specified cricket matches in the storage.
     *
     * @param int $id
     * @param Illuminate\Http\Request $request
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function update($id, Request $request)
    {
        try {

            $data = $this->getData($request);

            $cricketMatches = CricketMatches::findOrFail($id);
            $cricketMatches->update($data);

            return redirect()->route('cricket_matches.index')
                ->with('success_message', 'Cricket Matches was successfully updated.');
        } catch (Exception $exception) {

            return back()->withInput()
                ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request. Check Both teams are not same.']);
        }
    }

    /**
     * Remove the specified cricket matches from the storage.
     *
     * @param int $id
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        try {
            $cricketMatches = CricketMatches::findOrFail($id);
            $cricketMatches->delete();

            return redirect()->route('cricket_matches.index')
                ->with('success_message', 'Cricket Matches was successfully deleted.');
        } catch (Exception $exception) {

            return back()->withInput()
                ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request. Check Both teams are not same.']);
        }
    }


    /**
     * Get the request's data from the request.
     *
     * @param Illuminate\Http\Request\Request $request
     * @return array
     */
    protected function getData(Request $request)
    {
        $rules = [
            'team_one' => 'string|min:1|nullable',
            'team_two' => 'string|min:1|nullable|different:team_one',
            'match_date' => 'string|min:1|nullable',
            'match_venue' => 'string|min:1|nullable',
            'match_result' => 'string|min:1|nullable',
        ];


        $data = $request->validate($rules);




        return $data;
    }

}

resources/views/cricket_matches/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">

        <div class="panel-heading clearfix">

            <span class="pull-left">
                <h4 class="mt-5 mb-5">Create New Cricket Matches</h4>
            </span>

            <div class="btn-group btn-group-sm pull-right" role="group">
                <a href="{{ route('cricket_matches.index') }}" class="btn btn-primary" title="Show All Cricket Matches">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                </a>
            </div>

        </div>

        <div class="panel-body">

            @if ($errors->any())
                <ul class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif

            <form method="POST" action="{{ route('cricket_matches.store') }}" accept-charset="UTF-8" id="create_cricket_matches_form" name="create_cricket_matches_form" class="form-horizontal">
            {{ csrf_field() }}
            @include ('cricket_matches.form', [
                                        'cricketMatches' => null,
                                      ])

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input class="btn btn-primary" type="submit" value="Add">
                    </div>
                </div>

            </form>

        </div>
    </div>

@endsection

resources/views/cricket_matches/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">

        <div class="panel-heading clearfix">

            <div class="pull-left">
                <h4 class="mt-5 mb-5">{{ !empty($title) ? $title : 'Cricket Matches' }}</h4>
            </div>
            <div class="btn-group btn-group-sm pull-right" role="group">

                <a href="{{ route('cricket_matches.index') }}" class="btn btn-primary" title="Show All Cricket Matches">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                </a>

                <a href="{{ route('cricket_matches.create') }}" class="btn btn-success" title="Create New Cricket Matches">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </a>

            </div>
        </div>

        <div class="panel-body">

            @if ($errors->any())
                <ul class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif

            <form method="POST" action="{{ route('cricket_matches.update', $cricketMatches->id) }}" id="edit_cricket_matches_form" name="edit_cricket_matches_form" accept-charset="UTF-8" class="form-horizontal">
            {{ csrf_field() }}
            <input name="_method" type="hidden" value="PUT">
            @include ('cricket_matches.form', [
                                        'cricketMatches' => $cricketMatches,
                                      ])

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input class="btn btn-primary" type="submit" value="Update">
                    </div>
                </div>
            </form>

        </div>
    </div>

@endsection

resources/views/cricket_matches/form.blade.php
<div class="form-group {{ $errors->has('team_one') ? 'has-error' : '' }}">
    <label for="team_one" class="col-md-2 control-label">Team One*</label>
    <div class="col-md-10">
      <select class="form-control" id="team_one" name="team_one" required>
        <option value="" style="display: none;" {{ old('team_one', optional($cricketMatches)->team_one ?: '') == '' ? 'selected' : '' }} disabled selected>Select team</option>
        @foreach ($teams as $key => $team)
        <option value="{{ $key }}" {{ old('team_two', optional($cricketMatches)->team_one) == $key ? 'selected' : '' }}>
          {{ $team }}
        </option>
        @endforeach
      </select>
        <!-- <input class="form-control" name="team_one" type="text" id="team_one" value="{{ old('team_one', optional($cricketMatches)->team_one) }}" minlength="1" placeholder="Enter team one here..."> -->
        {!! $errors->first('team_one', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('team_two') ? 'has-error' : '' }}">
    <label for="team_two" class="col-md-2 control-label">Team Two*</label>
    <div class="col-md-10">
      <select class="form-control" id="team_two" name="team_two" required>
        <option value="" style="display: none;" {{ old('team_two', optional($cricketMatches)->team_two ?: '') == '' ? 'selected' : '' }} disabled selected>Select team</option>
        @foreach ($teams as $key => $team)
        <option value="{{ $key }}" {{ old('team_two', optional($cricketMatches)->team_two) == $key ? 'selected' : '' }}>
          {{ $team }}
        </option>
        @endforeach
      </select>
        <!-- <input class="form-control" name="team_two" type="text" id="team_two" value="{{ old('team_two', optional($cricketMatches)->team_two) }}" minlength="1" placeholder="Enter team two here..."> -->
        {!! $errors->first('team_two', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('match_date') ? 'has-error' : '' }}">
    <label for="match_date" class="col-md-2 control-label">Match Date</label>
    <div class="col-md-10">
        <input class="form-control" name="match_date" type="text" id="match_date" value="{{ old('match_date', optional($cricketMatches)->match_date) }}" placeholder="Enter match date here...">
        {!! $errors->first('match_date', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('match_venue') ? 'has-error' : '' }}">
    <label for="match_venue" class="col-md-2 control-label">Match Venue</label>
    <div class="col-md-10">
        <input class="form-control" name="match_venue" type="text" id="match_venue" value="{{ old('match_venue', optional($cricketMatches)->match_venue) }}" minlength="1" placeholder="Enter match venue here...">
        {!! $errors->first('match_venue', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<script type="text/javascript">
  jQuery(document).ready(function($) {
       $('#match_date').datepicker({
           autoclose: true,
           format: 'yyyy-mm-dd'
        });
     });
</script>

  @if(optional($cricketMatches)->id)
  <h4 style="color:green"><b>Select Winner team</b> </h4>
   <div class="form-group {{ $errors->has('match_result') ? 'has-error' : '' }}">
    <label for="match_result" class="col-md-2 control-label">Match Result</label>
    <div class="col-md-10">
      <select class="form-control" id="match_result" name="match_result" required>
        <option value="" style="display: none;" {{ old('match_result', optional($cricketMatches)->match_result ?: '') == '' ? 'selected' : '' }} disabled selected>Select winner team</option>
        @foreach ($teams as $key => $team)
          @if(optional($cricketMatches)->team_one ==  $key || optional($cricketMatches)->team_two ==  $key)
          <option value="{{ $key }}" {{ old('match_result', optional($cricketMatches)->match_result) == $key ? 'selected' : '' }}>
            {{ $team }}
          </option>
          @endif
        @endforeach
      </select>
        <!-- <input class="form-control" name="match_result" type="text" id="match_result" value="{{ old('match_result', optional($cricketMatches)->match_result) }}" minlength="1" placeholder="Enter match result here..."> -->
        {!! $errors->first('match_result', '<p class="help-block">:message</p>') !!}
    </div>
  </div>
  @endif

resources/views/cricket_matches/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">

        <div class="panel-heading clearfix">

            <div class="pull-left">
                <h4 class="mt-5 mb-5">Cricket Matches</h4>
            </div>

            <div class="btn-group btn-group-sm pull-right" role="group">
                <a href="{{ route('cricket_matches.create') }}" class="btn btn-success" title="Create New Cricket Matches">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </a>
            </div>

        </div>

        @if(count($cricketMatchesObjects) == 0)
            <div class="panel-body text-center">
                <h4>No Cricket Matches Available.</h4>
            </div>
        @else
        <div class="panel-body panel-body-with-table">
            <div class="table-responsive">
                <table class="table table-striped ">
                    <thead>
                        <tr>
                            <th>Team One</th>
                            <th>Team Two</th>
                            <th>Match Date</th>
                            <th>Match Venue</th>
                            <th>Match Winner</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($cricketMatchesObjects as $cricketMatches)
                        <tr>
                            <td>{{optional($cricketMatches->team_a)->team_name}}</td>
                            <td>{{optional($cricketMatches->team_b)->team_name}}</td>
                            <td>{{ $cricketMatches->match_date }}</td>
                            <td>{{ $cricketMatches->match_venue }}</td>
                            <td>{{ ($cricketMatches->match_result) ? optional($cricketMatches->team_winner)->team_name : 'Pending' }} </td>
                            <td>
                                <form method="POST" action="{!! route('cricket_matches.destroy', $cricketMatches->id) !!}" accept-charset="UTF-8">
                                <input name="_method" value="DELETE" type="hidden">
                                {{ csrf_field() }}
                                    <div class="btn-group btn-group-xs pull-right" role="group">
                                        <!-- <a href="{{ route('cricket_matches.show', $cricketMatches->id ) }}" class="btn btn-info" title="Show Cricket Matches">
                                            <span class="glyphicon glyphicon-open" aria-hidden="true"></span>
                                        </a> -->
                                        <a href="{{ route('cricket_matches.edit', $cricketMatches->id ) }}" class="btn btn-primary" title="Edit Cricket Matches">
                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                        </a>
                                        <button type="submit" class="btn btn-danger" title="Delete Cricket Matches" onclick="return confirm(&quot;Click Ok to delete Cricket Matches.&quot;)">
                                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                        </button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <div class="panel-footer">
            {!! $cricketMatchesObjects->render() !!}
        </div>
        @endif
    </div>
@endsection

resources/views/cricket_matches/matchPoints.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">
        <div class="panel-heading clearfix">
            <div class="pull-left">
                <h4 class="mt-5 mb-5">Cricket Matches Points</h4>
            </div>
        </div>
        @if(count($team_data) == 0)
            <div class="panel-body text-center">
                <h4>No Team Points Available.</h4>
            </div>
        @else

        <div class="panel-body panel-body-with-table">
            <div class="table-responsive">
                <table class="table table-striped ">
                    <thead>
                        <tr>
                            <th>Teams</th>
                            <th>Played</th>
                            <th>Win</th>
                            <th>Loose</th>
                            <th>No result</th>
                        </tr>
                    </thead>
                    <tbody>

                    @foreach($team_data as $team)
            
                        <tr>
                            <td>{{ $team['name'] }}</td>
                            <td>{{ $team['team_matches'] }}</td>
                            <td>{{ $team['team_win_count'] }}</td>
                            <td>{{ $team['team_loose_count'] }}</td>
                            <td>{{ $team['team_no_result'] }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <div class="panel-footer">

        </div>
        @endif
    </div>
@endsection

resources/views/cricket_matches/show.blade.php
@extends('layouts.app')

@section('content')

<div class="panel panel-default">
    <div class="panel-heading clearfix">

        <span class="pull-left">
            <h4 class="mt-5 mb-5">{{ isset($title) ? $title : 'Cricket Matches' }}</h4>
        </span>

        <div class="pull-right">

            <form method="POST" action="{!! route('cricket_matches.destroy', $cricketMatches->id) !!}" accept-charset="UTF-8">
            <input name="_method" value="DELETE" type="hidden">
            {{ csrf_field() }}
                <div class="btn-group btn-group-sm" role="group">
                    <a href="{{ route('cricket_matches.index') }}" class="btn btn-primary" title="Show All Cricket Matches">
                        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    </a>

                    <a href="{{ route('cricket_matches.create') }}" class="btn btn-success" title="Create New Cricket Matches">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </a>

                    <a href="{{ route('cricket_matches.edit', $cricketMatches->id ) }}" class="btn btn-primary" title="Edit Cricket Matches">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </a>

                    <button type="submit" class="btn btn-danger" title="Delete Cricket Matches" onclick="return confirm(&quot;Click Ok to delete Cricket Matches.?&quot;)">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </div>
            </form>

        </div>

    </div>

    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Team One</dt>
            <dd>{{ $cricketMatches->team_one }}</dd>
            <dt>Team Two</dt>
            <dd>{{ $cricketMatches->team_two }}</dd>
            <dt>Match Date</dt>
            <dd>{{ $cricketMatches->match_date }}</dd>
            <dt>Match Venue</dt>
            <dd>{{ $cricketMatches->match_venue }}</dd>
            <dt>Match Result</dt>
            <dd>{{ $cricketMatches->match_result }}</dd>

        </dl>

    </div>
</div>

@endsection