routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['middleware' => ['auth']], function() {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('teams', 'TeamsController');
    Route::resource('team_players', 'TeamPlayersController');

    //need these after search
    Route::post('/team_players', 'TeamPlayersController@index')->name('team_players.search');
    Route::post('/team_players/store', 'TeamPlayersController@store')->name('team_players.store');

    // routes for matches
    Route::resource('cricket_matches', 'CricketMatchesController');

    Route::get('/points', 'CricketMatchesController@points')->name('team.points');
});

app/Models/TeamPlayer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TeamPlayer extends Model
{


    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'team_players';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
                  'team_id',
                  'first_name',
                  'last_name',
                  'imageUri',
                  'player_jerseyno',
                  'dob',
                  'country',
                  'matches',
                  'run',
                  'highest_scores',
                  'fifties',
                  'hundreds',
                  'player_type'
              ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [];

    /**
     * Get the team for this model.
     *
     * @return App\Models\Team
     */
    public function team()
    {
        return $this->belongsTo('App\Models\Team','team_id');
    }



}

app/Http/Controllers/TeamPlayersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Team;
use App\Models\TeamPlayer;
use Illuminate\Http\Request;
use Exception;

class TeamPlayersController extends Controller
{

    /**
     * Display a listing of the team players.
     *
     * @return Illuminate\View\View
     */
    public function index(Request $request)
    {
        $uuid = $request->input('uuid');
        $team_id = $request->input('team_id');
        if ($request->isMethod('post')) {
          $teamPlayers = TeamPlayer::where('team_id', $team_id)->paginate($this->pageSize);
        }else{
          $teamPlayers = TeamPlayer::with('team')->paginate($this->pageSize);
        }
        $teams = Team::pluck('team_name','id')->all();
        // $teams = Team::where('is_active',1)->pluck('team_name','id');
        return view('team_players.index', compact('teamPlayers','teams','uuid','team_id'));
    }

    /**
     * Show the form for creating a new team player.
     *
     * @return Illuminate\View\View
     */
    public function create()
    {
        $teams = Team::pluck('team_name','id')->all();

        return view('team_players.create', compact('teams'));
    }

    /**
     * Store a new team player in the storage.
     *
     * @param Illuminate\Http\Request $request
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        try {
            $file = $request->file('imageUri');
            if(isset($file)){

              //File Details
              $filename = $file->getClientOriginalName();
              $extension = $file->getClientOriginalExtension();
              $tempPath = $file->getRealPath();
              $fileSize = $file->getSize();
              $mimeType = $file->getMimeType();
            }else{
              $extension= $filename= '';
            }
            $valid_extension = array("jpeg","png","jpg");
            $data = $this->getData($request);
            $data['imageUri'] = $filename;
            TeamPlayer::create($data);
            // Check file extension
             if(in_array(strtolower($extension),$valid_extension)){
               // File upload location
               $location = 'uploads/team_players';
               $file->move(public_path($location), $filename);
             }

            return redirect()->route('team_players.index')
                ->with('success_message', 'Team Player was successfully added.');
        } catch (Exception $exception) {

            return back()->withInput()
                ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }

    /**
     * Display the specified team player.
     *
     * @param int $id
     *
     * @return Illuminate\View\View
     */
    public function show($id)
    {
        $teamPlayer = TeamPlayer::with('team')->findOrFail($id);

        return view('team_players.show', compact('teamPlayer'));
    }

    /**
     * Show the form for editing the specified team player.
     *
     * @param int $id
     *
     * @return Illuminate\View\View
     */
    public function edit($id)
    {
        $teamPlayer = TeamPlayer::findOrFail($id);
        $teams = Team::pluck('team_name','id')->all();

        return view('team_players.edit', compact('teamPlayer','teams'));
    }

    /**
     * Update the specified team player in the storage.
     *
     * @param int $id
     * @param Illuminate\Http\Request $request
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function update($id, Request $request)
    {
        try {
            $file = $request->file('imageUri');
            if(isset($file)){

              //File Details
              $filename = $file->getClientOriginalName();
              $extension = $file->getClientOriginalExtension();
              $tempPath = $file->getRealPath();
              $fileSize = $file->getSize();
              $mimeType = $file->getMimeType();
            }else{
              $extension= $filename= '';
            }
            $valid_extension = array("jpeg","png","jpg");
            $data = $this->getData($request);
            if($filename!=''){
              $data['imageUri'] = $filename;
            }
            $teamPlayer = TeamPlayer::findOrFail($id);
            $teamPlayer->update($data);
            // Check file extension
             if(in_array(strtolower($extension),$valid_extension)){
               // File upload location
               $location = 'uploads/team_players';
               $file->move(public_path($location), $filename);
             }
            return redirect()->route('team_players.index')
                ->with('success_message', 'Team Player was successfully updated.');
        } catch (Exception $exception) {

            return back()->withInput()
                ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }

    /**
     * Remove the specified team player from the storage.
     *
     * @param int $id
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        try {
            $teamPlayer = TeamPlayer::findOrFail($id);
            $teamPlayer->delete();

            return redirect()->route('team_players.index')
                ->with('success_message', 'Team Player was successfully deleted.');
        } catch (Exception $exception) {

            return back()->withInput()
                ->withErrors(['unexpected_error' => 'Unexpected error occurred while trying to process your request.']);
        }
    }


    /**
     * Get the request's data from the request.
     *
     * @param Illuminate\Http\Request\Request $request
     * @return array
     */
    protected function getData(Request $request)
    {
        $rules = [
            'team_id' => 'nullable',
            'first_name' => 'required|string|min:1|nullable',
            'last_name' => 'required|string|min:1|nullable',
            'imageUri' =>'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            //'imageUri' => 'string|min:1|nullable',
            'player_jerseyno' => 'numeric|min:1|nullable',
            //'player_jerseyno' => 'string|min:1|nullable',
            'dob' => 'string|min:1|nullable',
            'country' => 'string|min:1|nullable',
            'matches' => 'numeric|min:1|nullable',
            'run' => 'numeric|min:1|nullable',
            'highest_scores' => 'numeric|min:1|nullable',
            'fifties' => 'numeric|min:1|nullable',
            'hundreds' => 'numeric|min:1|nullable',
            'player_type' => 'required|string|min:1|nullable',

        ];


        $data = $request->validate($rules);


        $data['is_active'] = $request->has('is_active');


        return $data;
    }

}

resources/views/team_players/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">

        <div class="panel-heading clearfix">

            <span class="pull-left">
                <h4 class="mt-5 mb-5">Create New Team Player</h4>
            </span>

            <div class="btn-group btn-group-sm pull-right" role="group">
                <a href="{{ route('team_players.index') }}" class="btn btn-primary" title="Show All Team Player">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                </a>
            </div>

        </div>

        <div class="panel-body">

            @if ($errors->any())
                <ul class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif

            <form method="POST" action="{{ route('team_players.store') }}" accept-charset="UTF-8" id="create_team_player_form" name="create_team_player_form" class="form-horizontal" enctype="multipart/form-data">
            {{ csrf_field() }}
            @include ('team_players.form', [
                                        'teamPlayer' => null,
                                      ])

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input class="btn btn-primary" type="submit" value="Add">
                    </div>
                </div>

            </form>

        </div>
    </div>

@endsection

resources/views/team_players/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">

        <div class="panel-heading clearfix">

            <div class="pull-left">
                <h4 class="mt-5 mb-5">{{ !empty($title) ? $title : 'Team Player' }}</h4>
            </div>
            <div class="btn-group btn-group-sm pull-right" role="group">

                <a href="{{ route('team_players.index') }}" class="btn btn-primary" title="Show All Team Player">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                </a>

                <a href="{{ route('team_players.create') }}" class="btn btn-success" title="Create New Team Player">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </a>

            </div>
        </div>

        <div class="panel-body">

            @if ($errors->any())
                <ul class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif

            <form method="POST" action="{{ route('team_players.update', $teamPlayer->id) }}" id="edit_team_player_form" name="edit_team_player_form" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input name="_method" type="hidden" value="PUT">
            @include ('team_players.form', [
                                        'teamPlayer' => $teamPlayer,
                                      ])

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input class="btn btn-primary" type="submit" value="Update">
                    </div>
                </div>
            </form>

        </div>
    </div>

@endsection

resources/views/team_players/form.blade.php
<div class="form-group {{ $errors->has('team_id') ? 'has-error' : '' }}">
    <label for="team_id" class="col-md-2 control-label">Team*</label>
    <div class="col-md-10">
        <select class="form-control" id="team_id" name="team_id" required>
        	<option value="" style="display: none;" {{ old('team_id', optional($teamPlayer)->team_id ?: '') == '' ? 'selected' : '' }} disabled selected>Select team</option>
        	@foreach ($teams as $key => $team)
			    <option value="{{ $key }}" {{ old('team_id', optional($teamPlayer)->team_id) == $key ? 'selected' : '' }}>
			    	{{ $team }}
			    </option>
			@endforeach
        </select>

        {!! $errors->first('team_id', '<p class="help-block">:message</p>') !!}
    </div>
</div>



<div class="form-group {{ $errors->has('first_name') ? 'has-error' : '' }}">
    <div class="col-md-6 {{ $errors->has('first_name') ? 'has-error' : '' }}">
      <label for="first_name" class="col-md-4 form-label-right control-label">First Name*</label>
      <div class="col-md-8">
        <input class="form-control" name="first_name" type="text" id="first_name" value="{{ old('first_name', optional($teamPlayer)->first_name) }}" minlength="1" placeholder="Enter first name here..." required>
        {!! $errors->first('first_name', '<p class="help-block">:message</p>') !!}
      </div>
    </div>

    <div class="col-md-6 {{ $errors->has('last_name') ? 'has-error' : '' }}">
      <label for="last_name" class="col-md-4 form-label-right control-label">Last Name*</label>
      <div class="col-md-8">
          <input class="form-control" name="last_name" type="text" id="last_name" value="{{ old('last_name', optional($teamPlayer)->last_name) }}" minlength="1" placeholder="Enter last name here..." required>
          {!! $errors->first('last_name', '<p class="help-block">:message</p>') !!}
      </div>
    </div>
</div>
<div class="form-group ">
    <div class="col-md-6 {{ $errors->has('imageUri') ? 'has-error' : '' }}">
    <label for="imageUri" class="col-md-4 form-label-right control-label">Image</label>
    <div class="col-md-8">
        <input class="form-control" name="imageUri" type="file" id="imageUri" value="{{ old('imageUri', optional($teamPlayer)->imageUri) }}" minlength="1" placeholder="Enter logo uri here...">
        (max file upload size upto 2MB, File type:  "jpeg","png","jpg")
        <br>
          @php
            $location = '/public/uploads/team_players';
          @endphp
          @if(optional($teamPlayer)->imageUri)
            <img src="{{url($location)}}/{{optional($teamPlayer)->imageUri }}" width="200" height="100">
          @endif
        <!-- <input class="form-control" name="imageUri" type="text" id="imageUri" value="{{ old('imageUri', optional($teamPlayer)->imageUri) }}" placeholder="Enter image uri here..."> -->
        {!! $errors->first('imageUri', '<p class="help-block">:message</p>') !!}
    </div>
  </div>
  <div class="col-md-6 {{ $errors->has('player_jerseyno') ? 'has-error' : '' }}">
    <label for="player_jerseyno" class="col-md-4 form-label-right control-label">Player Jerseyno</label>
    <div class="col-md-8">
        <input class="form-control" name="player_jerseyno" type="number" id="player_jerseyno" value="{{ old('player_jerseyno', optional($teamPlayer)->player_jerseyno) }}" minlength="1" placeholder="Enter player jerseyno here...">
        {!! $errors->first('player_jerseyno', '<p class="help-block">:message</p>') !!}
    </div>
  </div>
</div>

<div class="form-group">
  <div class="col-md-6 {{ $errors->has('dob') ? 'has-error' : '' }}">

    <label for="dob" class="col-md-4 form-label-right control-label">Dob</label>
    <div class="col-md-8">
        <input class="form-control" name="dob" type="text" id="dob" value="{{ old('dob', optional($teamPlayer)->dob) }}" minlength="1" placeholder="Enter dob here...">
        {!! $errors->first('dob', '<p class="help-block">:message</p>') !!}
    </div>
  </div>

  <div class="col-md-6 {{ $errors->has('country') ? 'has-error' : '' }}">
      <label for="country" class="col-md-4 form-label-right control-label">Country</label>
      <div class="col-md-8">
          <input class="form-control" name="country" type="text" id="country" value="{{ old('country', optional($teamPlayer)->country) }}" placeholder="Enter country here...">
          {!! $errors->first('country', '<p class="help-block">:message</p>') !!}
      </div>
  </div>
</div>

<div class="form-group">
  <div class="col-md-6 {{ $errors->has('matches') ? 'has-error' : '' }}">

    <label for="matches" class="col-md-4 form-label-right control-label">Matches</label>
    <div class="col-md-8">
        <input class="form-control" name="matches" type="number" id="matches" value="{{ old('matches', optional($teamPlayer)->matches) }}" minlength="1" placeholder="Enter matches here...">
        {!! $errors->first('matches', '<p class="help-block">:message</p>') !!}
    </div>
  </div>

  <div class="col-md-6 {{ $errors->has('run') ? 'has-error' : '' }}">
      <label for="run" class="col-md-4 form-label-right control-label">Run</label>
      <div class="col-md-8">
          <input class="form-control" name="run" type="number" id="run" value="{{ old('run', optional($teamPlayer)->run) }}" minlength="1" placeholder="Enter run here...">
          {!! $errors->first('run', '<p class="help-block">:message</p>') !!}
      </div>
  </div>
</div>

<div class="form-group">
  <div class="col-md-6 {{ $errors->has('highest_scores') ? 'has-error' : '' }}">

    <label for="highest_scores" class="col-md-4 form-label-right control-label">Highest Scores</label>
    <div class="col-md-8">
        <input class="form-control" name="highest_scores" type="number" id="highest_scores" value="{{ old('highest_scores', optional($teamPlayer)->highest_scores) }}" minlength="1" placeholder="Enter highest scores here...">
        {!! $errors->first('highest_scores', '<p class="help-block">:message</p>') !!}
    </div>
  </div>

  <div class="col-md-6 {{ $errors->has('fifties') ? 'has-error' : '' }}">
      <label for="fifties" class="col-md-4 form-label-right control-label">Fifties</label>
      <div class="col-md-8">
          <input class="form-control" name="fifties" type="number" id="fifties" value="{{ old('fifties', optional($teamPlayer)->fifties) }}" minlength="1" placeholder="Enter fifties here...">
          {!! $errors->first('fifties', '<p class="help-block">:message</p>') !!}
      </div>
  </div>
</div>

<div class="form-group">
  <div class="col-md-6 {{ $errors->has('hundreds') ? 'has-error' : '' }}">

    <label for="hundreds" class="col-md-4 form-label-right control-label">Hundreds</label>
    <div class="col-md-8">
        <input class="form-control" name="hundreds" type="number" id="hundreds" value="{{ old('hundreds', optional($teamPlayer)->hundreds) }}" minlength="1" placeholder="Enter hundreds here...">
        {!! $errors->first('hundreds', '<p class="help-block">:message</p>') !!}
    </div>
  </div>
  <div class="col-md-6 {{ $errors->has('player_type') ? 'has-error' : '' }}">

    <label for="hundreds" class="col-md-4 form-label-right control-label">Player Type*</label>
    <div class="col-md-8">
      <select class="form-control" id="player_type" name="player_type" required>
        <option value="" style="display: none;" {{ old('player_type', optional($teamPlayer)->player_type ?: '') == '' ? 'selected' : '' }} disabled selected>Select Player Type</option>
        <option value="Batsman" {{ old('team_id', optional($teamPlayer)->player_type) == 'Batsman' ? 'selected' : '' }}>Batsman</option>
        <option value="Bowler" {{ old('team_id', optional($teamPlayer)->player_type) == 'Bowler' ? 'selected' : '' }}>Bowler</option>
        <option value="All-rounder" {{ old('team_id', optional($teamPlayer)->player_type) == 'All-rounder' ? 'selected' : '' }}>All rounder</option>
      </select>
        {!! $errors->first('hundreds', '<p class="help-block">:message</p>') !!}
    </div>
  </div>
</div>
<script type="text/javascript">
  jQuery(document).ready(function($) {
       $('#dob').datepicker({
           autoclose: true,
           format: 'yyyy-mm-dd'
        });
     });
</script>

resources/views/team_players/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">

        <div class="panel-heading clearfix">
            <div class="pull-left">
                <h4 class="mt-5 mb-5">Team Players</h4>
            </div>
        </div>
        <div class="panel-body">
            <!-- customer search form start !-->
            <form action="{{ route('team_players.search') }}" method="post">
              {{ csrf_field() }}
              {{ method_field('POST') }}
                <input id="uuid" type="hidden" class="form-control" name="uuid" value="{{$uuid}}" />

                    <div class="form-group">
                        <label for="customer_location" class="col-md-2 control-label">{{__('Team')}}:</label>
                        <div class="col-md-4">
                            <select class="form-control" id="team_id" name="team_id" required>
                              <option value="">Select team</option>
                              @foreach ($teams as $key => $team)
                              <option value="{{ $key }}" {{ $key==$team_id ? 'selected' : ''}}  >
                                {{ $team }}
                              </option>
                              @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                 <br>
                                <button type="submit" id="submit" class="btn btn-success pull-right">
                                    &#128269; {{ __('Search') }}
                                </button>
                            </div>
                    </div>
            </form>
             <!-- customer search form end !-->

          </div>
        <div class="panel-heading clearfix">
          <div class="btn-group btn-group-sm pull-right" role="group">
              <a href="{{ route('team_players.create') }}" class="btn btn-success" title="Create New Team Player">
                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
              </a>
          </div>

      </div>
        @if(count($teamPlayers) == 0)
            <div class="panel-body text-center">
                <h4>No Team Players Available.</h4>
            </div>
        @else
        <div class="panel-body panel-body-with-table">
            <div class="table-responsive">
              @php
              $location = '/public/uploads/team_players';
              @endphp
                <table class="table table-striped ">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Team</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Player type</th>
                            <th>Image Uri</th>
                            <th>Player Jerseyno</th>
                            <th>Dob</th>
                            <th>Country</th>
                            <th>Matches</th>
                            <th>Run</th>
                            <th>Highest Scores</th>
                            <th>Fifties</th>
                            <th>Hundreds</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($teamPlayers as $key=>$teamPlayer)
                        <tr>
                            <td>{{ ++$key }}</td>
                            <td>{{ optional($teamPlayer->team)->team_name }}</td>
                            <td>{{ $teamPlayer->first_name }}</td>
                            <td>{{ $teamPlayer->last_name }}</td>
                            <td>{{ $teamPlayer->player_type }}</td>
                            <td>{{ $teamPlayer->imageUri }}
                            @if(optional($teamPlayer)->imageUri)
                            <br><img src="{{url($location)}}/{{$teamPlayer->imageUri }}" width="80" height="80"></td>
                            @endif
                            <td>{{ $teamPlayer->player_jerseyno }}</td>
                            <td>{{ $teamPlayer->dob }}</td>
                            <td>{{ $teamPlayer->country }}</td>
                            <td>{{ $teamPlayer->matches }}</td>
                            <td>{{ $teamPlayer->run }}</td>
                            <td>{{ $teamPlayer->highest_scores }}</td>
                            <td>{{ $teamPlayer->fifties }}</td>
                            <td>{{ $teamPlayer->hundreds }}</td>
                            <td>

                                <form method="POST" action="{!! route('team_players.destroy', $teamPlayer->id) !!}" accept-charset="UTF-8">
                                <input name="_method" value="DELETE" type="hidden">
                                {{ csrf_field() }}

                                    <div class="btn-group btn-group-xs pull-right" role="group">
                                        <a href="{{ route('team_players.show', $teamPlayer->id ) }}" class="btn btn-info" title="Show Team Player">
                                            <span class="glyphicon glyphicon-open" aria-hidden="true"></span>
                                        </a>
                                        <a href="{{ route('team_players.edit', $teamPlayer->id ) }}" class="btn btn-primary" title="Edit Team Player">
                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                        </a>

                                        <button type="submit" class="btn btn-danger" title="Delete Team Player" onclick="return confirm(&quot;Click Ok to delete Team Player.&quot;)">
                                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                        </button>
                                    </div>

                                </form>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>

        <div class="panel-footer">
            {!! $teamPlayers->render() !!}
        </div>

        @endif

    </div>
@endsection

resources/views/team_players/show.blade.php
@extends('layouts.app')

@section('content')

<div class="panel panel-default">
    <div class="panel-heading clearfix">

        <span class="pull-left">
            <h4 class="mt-5 mb-5">{{ isset($title) ? $title : 'Team Player' }}</h4>
        </span>

        <div class="pull-right">

            <form method="POST" action="{!! route('team_players.destroy', $teamPlayer->id) !!}" accept-charset="UTF-8">
            <input name="_method" value="DELETE" type="hidden">
            {{ csrf_field() }}
                <div class="btn-group btn-group-sm" role="group">
                    <a href="{{ route('team_players.index') }}" class="btn btn-primary" title="Show All Team Player">
                        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    </a>

                    <a href="{{ route('team_players.create') }}" class="btn btn-success" title="Create New Team Player">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </a>

                    <a href="{{ route('team_players.edit', $teamPlayer->id ) }}" class="btn btn-primary" title="Edit Team Player">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </a>

                    <button type="submit" class="btn btn-danger" title="Delete Team Player" onclick="return confirm(&quot;Click Ok to delete Team Player.?&quot;)">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </div>
            </form>

        </div>

    </div>

    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Team</dt>
            <dd>{{ optional($teamPlayer->team)->team_name }}</dd>
            <dt>First Name</dt>
            <dd>{{ $teamPlayer->first_name }}</dd>
            <dt>Last Name</dt>
            <dd>{{ $teamPlayer->last_name }}</dd>
            @php
            $location = '/public/uploads/team_players';
            @endphp
            @if(optional($teamPlayer)->imageUri)
            <dt>Image</dt>
            <dd>{{ $teamPlayer->imageUri }}</dd>
            <dd><img src="{{url($location)}}/{{$teamPlayer->imageUri }}" width="100" height="100"></dd>
            @endif
            <dt>Player Jerseyno</dt>
            <dd>{{ $teamPlayer->player_jerseyno }}</dd>
            <dt>Dob</dt>
            <dd>{{ $teamPlayer->dob }}</dd>
            <dt>Country</dt>
            <dd>{{ $teamPlayer->country }}</dd>
            <dt>Matches</dt>
            <dd>{{ $teamPlayer->matches }}</dd>
            <dt>Run</dt>
            <dd>{{ $teamPlayer->run }}</dd>
            <dt>Highest Scores</dt>
            <dd>{{ $teamPlayer->highest_scores }}</dd>
            <dt>Fifties</dt>
            <dd>{{ $teamPlayer->fifties }}</dd>
            <dt>Hundreds</dt>
            <dd>{{ $teamPlayer->hundreds }}</dd>

        </dl>

    </div>
</div>

@endsection